# Generated by Django 4.0.4 on 2022-05-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_profile_img',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
