# Generated by Django 4.0.4 on 2022-05-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryfile',
            name='df_filepath',
            field=models.ImageField(blank=True, null=True, upload_to='diary_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_profile_img',
            field=models.ImageField(blank=True, max_length=128, null=True, upload_to='user_profile/'),
        ),
    ]
