# Generated by Django 4.0.4 on 2022-05-18 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_diaryfile_df_filepath_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_profile_img',
        ),
    ]
